import { Heading, Text, Box } from "@chakra-ui/react";
import Head from "next/head";
import Business from "./HomeComponents/Business";
import Cta from "./HomeComponents/Cta";
import Finding from "./HomeComponents/Finding";
import Hero from "./HomeComponents/Hero";
import Metrics from "./HomeComponents/Metrics";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        backgroundImage={"/herobackground.png"}
        backgroundRepeat={"no-repeat"}
        backgroundSize={"cover"}
      >
        <Hero />
        <Business />
        <Cta />
        <Metrics />
        <Finding />
      </Box>
    </div>
  );
}
